GET http://localhost:4000/

###

GET http://localhost:4000/1

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "divardhia@gmail.com",
    "password": "1234567890"
}

###
POST http://localhost:4000/
Content-Type: application/json

{
    "nama": "sela auia",
    "email": "sela@email.com",
    "password": "1234567890"
}

###
PATCH  http://localhost:4000/2
Content-Type: application/json

{
    "nama": "sela aulia",
    "email": "sela@email.com",
    "password": "1234567890"
}

###
DELETE http://localhost:4000/2